timeout: 10m
steps:
  - id: go_deploy
    name: 'gcr.io/cloud-builders/gcloud'
    args: ['functions', 
    "deploy", "wm-$BRANCH_NAME-${_FUNCTION_NAME}", 
    "--entry-point", "${_ENTRY_POINT}", 
    "--runtime","go111", 
    "--memory", "256MB",
    "--trigger-topic", "wm-${_TRIGGER_TOPIC}-$BRANCH_NAME", 
    "--project", "${PROJECT_ID}", 
    "--timeout", "540",
    "--retry",
    "--env-vars-file", ".env.$BRANCH_NAME.yaml",
    "--vpc-connector", "${_VPC_CONNECTOR}"
    ]
    env: ['GOPATH=/gopath']
    dir: './cloud-functions/${_FUNCTION_NAME}/src'
tags: ['$BRANCH_NAME']    
substitutions:
    _FUNCTION_NAME: file-status
    _TRIGGER_TOPIC: filestatus
    _ENTRY_POINT: CheckStatus
options:
    substitution_option: 'ALLOW_LOOSE'