timeout: 600s
steps:
  - id: go_deploy_1
    name: 'gcr.io/cloud-builders/gcloud'
    args: ['functions', 
    "deploy", "wm-$BRANCH_NAME-${_FUNCTION_NAME}", 
    "--entry-point", "${_ENTRY_POINT}", 
    "--runtime","go111", 
    "--memory", "1024MB",
    "--trigger-topic", "wm-${_TRIGGER_TOPIC}-$BRANCH_NAME", 
    "--project", "${PROJECT_ID}", 
    "--timeout", "60",
    "--env-vars-file", ".env.$BRANCH_NAME.yaml",
    "--vpc-connector", "${_VPC_CONNECTOR}"
    ]
    env: ['GOPATH=/gopath']
    dir: './cloud-functions/${_FUNCTION_NAME}/src'
  - id: go_deploy_1
    name: 'gcr.io/cloud-builders/gcloud'
    args: ['functions', 
    "deploy", "wm-$BRANCH_NAME-${_FUNCTION_NAME}-api", 
    "--entry-point", "${_ENTRY_POINT}", 
    "--runtime","go111", 
    "--memory", "1024MB",
    "--trigger-topic", "wm-${_TRIGGER_TOPIC}-$BRANCH_NAME", 
    "--project", "${PROJECT_ID}", 
    "--timeout", "60",
    "--env-vars-file", ".env.$BRANCH_NAME.yaml",
    "--vpc-connector", "${_VPC_CONNECTOR}"
    ]
    env: ['GOPATH=/gopath']
    dir: './cloud-functions/${_FUNCTION_NAME}/src'    
tags: ['$BRANCH_NAME']    
substitutions:
    _FUNCTION_NAME: file-report-update
    _TRIGGER_TOPIC: file-report
    _ENTRY_POINT_1: ProcessUpdate
    _VPC_CONNECTOR: cf-connector-4
options:
    substitution_option: 'ALLOW_LOOSE'