timeout: 10m
steps:
  - id: git_fetch
    name: gcr.io/cloud-builders/git
    args: ['fetch', '--unshallow']
  - id: go_deploy
    name: 'gcr.io/cloud-builders/gcloud'
    args: ['functions', 
    'deploy','streamer-$BRANCH_NAME', 
    '--entry-point', 'FileStreamer', 
    '--runtime','go111', 
    '--trigger-bucket', "streamer-upload-$BRANCH_NAME",
    "--project", "${PROJECT_ID}", 
    "--env-vars-file", ".env.$BRANCH_NAME.yaml"
    ]
    env: ['GOPATH=/gopath']
    dir: './cloud-functions/streamer/src'
tags: ['$BRANCH_NAME']    
