timeout: 9m
steps:
  - id: go_deploy
    name: 'gcr.io/cloud-builders/gcloud'
    args: ['functions', 
    'deploy','wm-$BRANCH_NAME-abm-mapper', 
    '--entry-point', 'Main', 
    '--runtime','go111', 
    '--trigger-topic', 'wm-${_TRIGGER_TOPIC}-$BRANCH_NAME', 
    '--project', '${PROJECT_ID}',
    '--env-vars-file', '.env.$BRANCH_NAME.yaml',
    ]
    env: ['GOPATH=/gopath']
    dir: './cloud-functions/abm-mapper/src'
tags: ['$BRANCH_NAME']    
substitutions:
    _TRIGGER_TOPIC: topics-post
options:
    substitution_option: 'ALLOW_LOOSE'