timeout: 10m
steps:
  - id: go_deploy
    name: 'gcr.io/cloud-builders/gcloud'
    args: ['functions', 
    'deploy','wm-fileprocessor-$BRANCH_NAME', 
    '--entry-point', 'ProcessFile', 
    '--runtime','go111', 
    '--trigger-topic", "wm-eventfile-$BRANCH_NAME', 
    "--project", "${PROJECT_ID}", 
    "--clear-env-vars",
    "--timeout", "540",
    "--env-vars-file", ".env.$BRANCH_NAME.yaml"
    ]
    env: ['GOPATH=/gopath']
    dir: './cloud-functions/file-processor/src'
tags: ['$BRANCH_NAME']    
