timeout: 10m
steps:
  - id: go_deploy
    name: 'gcr.io/cloud-builders/gcloud'
    args: ['functions', 
    'deploy','streamer-api-$BRANCH_NAME', 
    '--entry-point', 'Main', 
    '--runtime','go111', 
    '--trigger-http', 
    "--project", "${PROJECT_ID}", 
    "--env-vars-file", ".env.$BRANCH_NAME.yaml"
    ]
    env: ['GOPATH=/gopath']
    dir: './cloud-functions/file-processor/src'
tags: ['$BRANCH_NAME']    
