timeout: 10m
steps:
- name: "gcr.io/cloud-builders/go"
  args: ["build", "cloud-functions/browser-id/src/browser-id.go"]
  env: [
    "GOARCH=amd64",
    "GOOS=linux",
    "CGO_ENABLED=0",
    "GOPATH=/workspace/cloud-functions/browser-id"
  ]  
- name: 'gcr.io/cloud-builders/gcloud'
  args: ['functions', 'deploy','browser-id-dev','--entry-point','Main', '--runtime','go111','--trigger-http', "--project", "${PROJECT_ID}", "--env-vars-file", ".env.$BRANCH_NAME.yaml"]
tags: ['$BRANCH_NAME']    