timeout: 10m
steps:
  - id: owner_upsert_deploy
    name: 'gcr.io/cloud-builders/gcloud'
    args: ['functions',
    "deploy", "wm-$BRANCH_NAME-${_FUNCTION_NAME}-push",
    "--entry-point", "Upsert",
    "--runtime","go111",
    "--trigger-http",
    "--project", "${PROJECT_ID}",
    "--timeout", "30",
    "--env-vars-file", ".env.$BRANCH_NAME.yaml"
    ]
    env: ['GOPATH=/gopath']
    dir: './cloud-functions/${_FUNCTION_NAME}/src'
tags: ['$BRANCH_NAME']
substitutions:
    _FUNCTION_NAME: owner-api
options:
    substitution_option: 'ALLOW_LOOSE'