timeout: 10m
steps:
  - id: go_deploy
    name: 'gcr.io/cloud-builders/gcloud'
    args: ['functions', 
    "deploy", "wm-$BRANCH_NAME-${_FUNCTION_NAME}", 
    "--entry-point", "${_ENTRY_POINT}", 
    "--runtime","go111", 
    "--trigger-topic", "wm-${_TRIGGER_TOPIC}-$BRANCH_NAME", 
    "--project", "${PROJECT_ID}", 
    "--timeout", "30",
    "--env-vars-file", ".env.$BRANCH_NAME.yaml",
    "--max-instances", "100"
    ]
    env: ['GOPATH=/gopath']
    dir: './cloud-functions/${_FUNCTION_NAME}/src'
tags: ['$BRANCH_NAME']    
substitutions:
    _FUNCTION_NAME: household-360
    _TRIGGER_TOPIC: people-postpipe
    _ENTRY_POINT: HouseHold360
options:
    substitution_option: 'ALLOW_LOOSE'