version: '3.4'
services:
  dev:
    build:
      context: .
      dockerfile: Dockerfile
    command: ["go", "run", "main.go"]
    working_dir: "/go/src/gitlab.com/wemade/ms/tmphackbrowseridserver"
    environment:
      - "PORT=3000"
    ports:
      - "3000:3000"
    volumes:
      - "./:/go/src/gitlab.com/wemade/ms/tmphackbrowseridserver"
      - "../keys:/keys"
