timeout: 10m
steps:
  - id: go_deploy
    name: 'gcr.io/cloud-builders/gcloud'
    args: ['functions', 
    "deploy", "wm-${_FUNCTION_NAME}-$BRANCH_NAME", 
    "--entry-point", "${_ENTRY_POINT}", 
    "--runtime","go111", 
    "--trigger-http", 
    "--project", "${PROJECT_ID}", 
    "--timeout", "30",
    "--env-vars-file", ".env.$BRANCH_NAME.yaml"
    ]
    env: ['GOPATH=/gopath']
    dir: './cloud-functions/${_FUNCTION_NAME}/src'
tags: ['$BRANCH_NAME']    
substitutions:
    _FUNCTION_NAME: file-api
    _ENTRY_POINT: ProcessEvent
options:
    substitution_option: 'ALLOW_LOOSE'